version: "3.9"
services:
  hub:
    image: tiangolo/uvicorn-gunicorn-starlette:python3.7
    container_name: hub
    #restart: unless-stopped
    env_file: .env
    ports:
      - "9999:80"
    volumes:
      - ./app:/app