version: "3.9"

services:
  portal:
    build: ./dockerfiles_main/portal
    container_name: portal
    #restart: unless-stopped
    #env_file: .env
    ports:
      - "1080:80"
    volumes:
      - ./app:/app
      - ./dockerfiles_users:/dockerfiles_users
      - ./ipc:/ipc
      - ./logs:/logs
    working_dir: /app
    networks:
      - app-network
    command: >
      sh -c "uvicorn app:app --reload --host 0.0.0.0 --port 80"


  launcher:
    build: ./dockerfiles_main/launcher
    container_name: launcher
    volumes:
    # Can run sibling containers with the below socket
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockerfiles_users:/dockerfiles_users
      - ./dockerfiles_main/libretranslate:/libretranslate
      - ./ipc:/ipc
      - ./launcher:/launcher
      - ./logs:/logs
    working_dir: /launcher
    networks:
      - app-network
#      - envNetwork
    # Need a prolonged grace stop period (normally 10 seconds) as otherwise the sibling containers to get closed in time
    stop_grace_period: 1m
    depends_on:
      - portal
    # use of entrypoint rather than command to make below function PID1, and can then handle SIGTERM appropriately (Linux treats PID1 a little different to other processes (harder to kill))
    entrypoint: sh -c "python launcher.py"


#  webserver:
#    depends_on:
#      - portal
#    image: nginx:1.15.12-alpine
#    container_name: webserver
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx-conf:/etc/nginx/conf.d
#    networks:
#      - app-network
#      - nginx-network
#      - envNetwork


networks:
  app-network:
    driver: bridge
#  nginx-network:
#    external: true
#  envNetwork:
#    name: envNetwork
