version: "3.9"
services:
  mkdocs:
    build: .
    container_name: mkdocs
    ports:
      - 8000:8000
    env_file:
      - ../.env
    volumes:
      - ../:/project
    working_dir: /project/docs
    command:
      #sh -c "./gh-deploy.sh"
      sh -c "while true; do moo; sleep 10; done"
