version: "3.9"
services:
  mkdocs:
    build: .
    container_name: mkdocs
    ports:
      - 8000:8000
    environment:
      - GH_user=${GH_user}
      - GH_token=${GH_token}
    volumes:
      - ../:/project
      #- ../app:/app
      #- ../docs:/docs
      #- ../launcher:/launcher
    working_dir: /project/docs
    command:
      #sh -c "mkdocs serve --dev-addr=0.0.0.0:8000"
      sh -c "./gh-deploy.sh"
