version: "3.9"
services:
  mkdocs:
    build: .
    container_name: mkdocs
    ports:
      - 8000:8000
      - 80:80
      - 433:433
    volumes:
      - ../app:/app
      - ../docs:/docs
      - ../launcher:/launcher
    working_dir: /docs
    command:
      sh -c "mkdocs gh-deploy --force"
