version: "3.9"
services:
  mkdocs:
    build: .
    container_name: mkdocs
    ports:
      - 8000:8000
    environment:
      - GH_user=${GH_user}
      - GH_token=${GH_token}
    volumes:
      - ../:/project
      - $GITHUB_WORKSPACE:$GITHUB_WORKSPACE
    working_dir: /project/docs
    command:
      sh -c "./gh-deploy.sh"
      #sh -c "while true; do moo; sleep 10; done"
