version: "3.9"
services:
  mkdocs:
    build: .
    container_name: mkdocs
    ports:
      #- 8000:8000
      - 80:80
      - 433:433
    volumes:
      - ../app:/app
      - ../docs:/docs
      - ../launcher:/launcher
    working_dir: /docs
    command:
      sh -c "mkdocs gh-deploy --force --config-file 'docs/mkdocs.yml'"
      #sh -c "mkdocs serve --dev-addr=0.0.0.0:8000"
      #sh -c "while true; do moo; sleep 2; done"
