name: 'MkDocs webpage'
on:
  push:
    branches:
      - master 
      - main

permissions:
  contents: write

jobs:
  vm:
    runs-on: ubuntu-latest
    container:
      build: /docs
      ports:
        - 80:80
        - 443:443
      volumes:
        - ../app:/app
        - ../docs:/docs
        - ../launcher:/launcher
      steps:  
         - name: Step with docker to echo a string
           uses: docker://node:12.14.1-alpine3.10
           with:
             entrypoint: /bin/echo
             args: Hello Docker !
#      steps:
#        - name: Start up mk-docs gh-deploy
#          run: mkdocs gh-deploy --force --config-file 'docs/mkdocs.yml'