name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu:20.04
    container:
      build: /docs
      container_name: mkdocs
      ports:
        - 80:80
        - 443:443
      volumes:
        - ../app:/app
        - ../docs:/docs
        - ../launcher:/launcher
      steps:
        - run: mkdocs gh-deploy --force --config-file 'docs/mkdocs.yml'