name: dockerMkdocs
on:
  push:
    branches:
      - master 
      - main
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GH_user: ${{ secrets.GH_user }}
      GH_token: ${{ secrets.GH_token }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and run
      run: docker compose --file ./docs/Docker-compose_GA.yml up