name: test
on:
  push:
    branches:
      - master 
      - main
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ECHO
      run: PWD
    - name: Build the Docker image
      run: cd ./docs && docker compose build