name: test
on:
  push:
    branches:
      - master 
      - main
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: cd
      run: cd ./docs
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: Build the Docker image and run
      run: docker compose --file ./docs/Docker-compose.yml up -d
      mkdocs gh-deploy --force --config-file 'docs/mkdocs.yml'